#!/bin/sh
set -e

userp=/home/c0rvax

cd $userp/.zsh

echo '#              DO NOT EDIT THIS FILE
# Add your own customizations in ~/.zsh/myconfig.zsh

source ~/.zsh/myconfig.zsh

# Type zshrc to edit config and then type szsh to apply changes' > $userp/.zshrc

git clone https://github.com/zsh-users/zsh-autosuggestions.git $userp/.oh-my-zsh/custom/plugins/zsh-autosuggestions || git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $userp/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting || git clone https://github.com/zdharma-continuum/fast-syntax-highlighting $userp/.oh-my-zsh/custom/plugins/fast-syntax-highlighting

echo "Installed the zshrc configuration successfully! Enjoy :-)"
