#!/bin/sh
set -e

cd ~/.zsh

echo '#              DO NOT EDIT THIS FILE
# Add your own customizations in ~/.zsh/myconfig.zsh

source ~/.zsh/myconfig.zsh' > ~/.zshrc

echo "Installed the zshrc configuration successfully! Enjoy :-)"
